//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OnlineShopping.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class Project_ShoppingEntities : DbContext
    {
        public Project_ShoppingEntities()
            : base("name=Project_ShoppingEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Cart> Carts { get; set; }
        public virtual DbSet<Category> Categories { get; set; }
        public virtual DbSet<Order> Orders { get; set; }
        public virtual DbSet<Product> Products { get; set; }
        public virtual DbSet<Retailer> Retailers { get; set; }
        public virtual DbSet<Update_Products> Update_Products { get; set; }
        public virtual DbSet<User> Users { get; set; }
        public virtual DbSet<Wishlist> Wishlists { get; set; }
    
        public virtual ObjectResult<GetAllCategory_Result> GetAllCategory()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllCategory_Result>("GetAllCategory");
        }
    
        public virtual ObjectResult<GetAllPdts_Result> GetAllPdts()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetAllPdts_Result>("GetAllPdts");
        }
    
        public virtual ObjectResult<GetOneCategory_Result> GetOneCategory(Nullable<int> catid)
        {
            var catidParameter = catid.HasValue ?
                new ObjectParameter("catid", catid) :
                new ObjectParameter("catid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GetOneCategory_Result>("GetOneCategory", catidParameter);
        }
    
        //public virtual ObjectResult<sp_getOrders_Result> sp_getOrders(Nullable<int> userid)
        //{
        //    var useridParameter = userid.HasValue ?
        //        new ObjectParameter("userid", userid) :
        //        new ObjectParameter("userid", typeof(int));
    
        //    return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOrders_Result>("sp_getOrders", useridParameter);
        //}
    
        public virtual ObjectResult<sp_getOrdersfromCart_Result> sp_getOrdersfromCart(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOrdersfromCart_Result>("sp_getOrdersfromCart", useridParameter);
        }
    
        public virtual int sp_ins_order(Nullable<int> id)
        {
            var idParameter = id.HasValue ?
                new ObjectParameter("id", id) :
                new ObjectParameter("id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("sp_ins_order", idParameter);
        }
    
        public virtual ObjectResult<sp_Pdts_Of_One_Category_Result> sp_Pdts_Of_One_Category(Nullable<int> cat_id)
        {
            var cat_idParameter = cat_id.HasValue ?
                new ObjectParameter("cat_id", cat_id) :
                new ObjectParameter("cat_id", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_Pdts_Of_One_Category_Result>("sp_Pdts_Of_One_Category", cat_idParameter);
        }
    
        public virtual ObjectResult<sp_getOrders1_Result> sp_getOrders1(Nullable<int> userid)
        {
            var useridParameter = userid.HasValue ?
                new ObjectParameter("userid", userid) :
                new ObjectParameter("userid", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<sp_getOrders1_Result>("sp_getOrders1", useridParameter);
        }
    }
}
